### ISSUE TITLE
How to convert many CSV files into a qframe?

### ISSUE THREAD

**Issue by TenZeroTwo** [tobgu/qframe#16]
I have many data source files like data_1.csv,data_2.csv,data_3.csv.
In "gota", I can use method "RBind"
`
		if fileN == 0 {
			dfAll = df.Copy()
		} else {
			dfAll = dfAll.RBind(df) 
		}
`
but qframe.ReadCSV is static function.
How to make a qframe read from 1+ csv ？

**Comment by tobgu** [comment]
The short answer is there is no equivalent functionality to `RBind` in QFrame ATM, simply because I haven't had the need for it.

Depending on your use case and ambition two possibilities pop up:
1. ReadCSV takes a `io.Reader` from which the input data is read. Pou can use the `io.MultiReader` from the stdlib (https://golang.org/pkg/io/#MultiReader) to "concatenate" your files. The crux here is that you want to get rid of the headers in the files first to avoid having these show up in the dataframe. This could be done by removing the first line of all files (either statically in the files or in a custom reader that you implement) and then pass the column names separately to `qframe.ReadCsv()` using the `Headers` function (https://godoc.org/github.com/tobgu/qframe/config/csv#Headers). 
2. You implement a more general `RBind`-like function to QFrame. I'd love to see a PR on this. As I said I haven't needed it myself but I can definitely see the use for it!

**Comment by TenZeroTwo** [comment]
At last, I chose the first one. In my scenario, the first/second row and the last row of the file  should be to remove, there are something about meta info like date,total.  Dropping the header while handling the meta info. And join the bytes of each file into another CSV.
Anyway, qframe is a great project !!! It will get more and more stars.

**Comment by tobgu** [comment]
Glad to hear that your problems are solved and thanks for your kind words!

I'll close this issue now since no immediate action is planned.
